### ISSUE TITLE
Example missing?

### ISSUE THREAD

**Issue by MostHated** [ashblue/fluid-behavior-tree#1]
Hello,
    In the examples, it looks like there is only a blank scene? Am I missing something by chance?

Thanks,
-MH

**Comment by ashblue** [comment]
Thanks for checking out the repo @MostHated. Just this weekend I finished a stable version of Fluid BT. You can find the release package with a CTF example as a package here https://github.com/ashblue/fluid-behavior-tree/releases/tag/version%2F1.0

I still need to finish the documentation (currently none in the Readme.md), a tree visualizer window, more examples, and some other pieces. Have a Trello board I should make public and post to the Readme.md as far as new features go. Hopefully over the next couple months I'll be updating the releases section with new features as I have time to roll these out. If you have any suggestions on how to improve things would love to hear them.

**Comment by ashblue** [comment]
@MostHated I love that you mention pre-made action libraries. I based a lot of the project on Fluent Behavior Tree and went through some painful extra lifting to make everything extremely extendable. That way people can contribute or create their own re-usable actions, conditions, inverters, ect. If you check the folders in scripts there should be some examples such as "Wait", "RandomChance", "ReturnSuccess", ect.

For your boss example, if I follow correctly (let me know if I'm off here). You could create ScriptableObject(s) (SOs) and pass them into your tree (or dynamically inject from an array of SOs). For example you could have an SO that handles targeting, then an attack action if the targeting is successful, and even add in a cooldown param for your delay. It would end up looking something like this.

```
...
  .HealthCondition(COMPARE_SO)
  .FindTarget(COMPARE_SO)
  .Attack(ATTACK_SO)
  .Cooldown(COOLDOWN_PARAM)
```

In the inspector you might bundle all that into a single SO with nested objects. Maybe something like AttackBundle.

I was doing something similar to this on a game project with Behavior Designer. The biggest pain is usually standardizing how you organize your data and coming up with good re-usable SOs. But after that you can create nice chunks of re-usable functionality to speed up prototyping.

**Comment by ashblue** [comment]
Note you'd have to extend the TreeBuilder script to do something pretty like the above example. But it should be pretty self explanatory when you look at the TreeBuilder code.

**Comment by ashblue** [comment]
If you're going to have an authoritative database I'd go with just having normal objects instead of SOs. SOs are mostly targeted at being able to tweak data in the inspector while working in Unity. PS You can just write your own `Load(string data)` and `Save()` methods to export and import your data to an SO.
